import { marked } from 'marked';

/**
 * Turns a run's tool-call results into a single, self-contained HTML file
 * you can open directly in a browser — content rendered from markdown
 * (so embedded ![]() images actually show as images, not raw syntax),
 * and every generated Cloudinary asset laid out as a real thumbnail grid
 * instead of a wall of URLs in a JSON file.
 */
export function buildHtmlReport({ launchSlug, results, summary }) {
  const contentTools = {
    generate_release_notes: 'Release notes',
    generate_blog_draft: 'Blog draft',
    generate_docs: 'Docs / details sheet',
    generate_social_posts: 'Social posts',
  };

  const contentSections = results
    .filter((r) => contentTools[r.tool] && r.output?.content)
    .map(
      (r) => `
      <section class="card">
        <h2>${contentTools[r.tool]}</h2>
        <div class="content">${marked.parse(r.output.content)}</div>
      </section>`
    )
    .join('\n');

  // Collect every image/video URL the run actually produced, regardless of
  // which tool made it, so the gallery reflects reality rather than an
  // assumed fixed set of asset types.
  const assetCards = [];
  for (const r of results) {
    if (r.tool === 'upload_launch_image' && r.output?.url) {
      assetCards.push({ label: `Uploaded: ${r.output.role || r.input.assetName}`, url: r.output.url });
    }
    if (r.tool === 'find_launch_assets' && Array.isArray(r.output?.assets)) {
      for (const a of r.output.assets) {
        assetCards.push({ label: `Found: ${a.role || a.publicId}`, url: a.url });
      }
    }
    if (r.tool === 'generate_social_crops' && r.output) {
      for (const [platform, url] of Object.entries(r.output)) {
        if (typeof url === 'string') assetCards.push({ label: `Crop: ${platform}`, url });
      }
    }
    if (r.tool === 'generate_og_image' && r.output?.url) {
      assetCards.push({ label: 'Open Graph image', url: r.output.url });
    }
    if (r.tool === 'generate_channel_assets' && r.output) {
      for (const [channel, url] of Object.entries(r.output)) {
        if (typeof url === 'string') assetCards.push({ label: `Channel: ${channel}`, url });
      }
    }
  }

  const isVideo = (url) => /\.(mp4|mov|webm)(\?|$)/i.test(url) || url.includes('/video/upload/');

  const assetGrid = assetCards.length
    ? assetCards
        .map(
          (a) => `
        <div class="asset">
          ${
            isVideo(a.url)
              ? `<video src="${a.url}" controls muted></video>`
              : `<img src="${a.url}" alt="${a.label}" loading="lazy" onerror="this.replaceWith(Object.assign(document.createElement('div'),{className:'broken',textContent:'Image not reachable — check your Cloudinary cloud name'}))">`
          }
          <p>${a.label}</p>
          <a href="${a.url}" target="_blank" rel="noopener">Open full URL ↗</a>
        </div>`
        )
        .join('\n')
    : '<p class="muted">No assets were produced in this run.</p>';

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>Launch report — ${launchSlug}</title>
<style>
  :root { color-scheme: light dark; }
  body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif; max-width: 860px; margin: 0 auto; padding: 2.5rem 1.5rem 5rem; line-height: 1.6; }
  h1 { font-size: 1.6rem; margin-bottom: 0.25rem; }
  .subtitle { color: #888; margin-top: 0; margin-bottom: 2rem; }
  .card { border: 1px solid #ddd; border-radius: 10px; padding: 1.25rem 1.5rem; margin-bottom: 1.5rem; }
  .card h2 { margin-top: 0; font-size: 1.1rem; }
  .content img { max-width: 100%; border-radius: 8px; margin: 0.75rem 0; }
  .content pre { background: #f4f4f4; padding: 0.75rem 1rem; border-radius: 6px; overflow-x: auto; }
  .summary { background: #f7f7f7; border-radius: 10px; padding: 1.25rem 1.5rem; margin-bottom: 2rem; white-space: pre-wrap; }
  .asset-section { margin-top: 2rem; }
  .asset-grid { display: grid; grid-template-columns: repeat(auto-fill, minmax(180px, 1fr)); gap: 1rem; }
  .asset { border: 1px solid #ddd; border-radius: 8px; padding: 0.75rem; text-align: center; }
  .asset img, .asset video { width: 100%; border-radius: 6px; aspect-ratio: 4/3; object-fit: cover; }
  .asset p { font-size: 0.85rem; margin: 0.5rem 0 0.25rem; }
  .asset a { font-size: 0.8rem; }
  .broken { padding: 1rem; background: #fdecea; border-radius: 6px; font-size: 0.8rem; color: #a33; }
  .muted { color: #888; }
  @media (prefers-color-scheme: dark) {
    body { background: #111; color: #eee; }
    .card, .asset { border-color: #333; }
    .content pre, .summary { background: #1c1c1c; }
    .broken { background: #3a1f1f; color: #e88; }
  }
</style>
</head>
<body>
  <h1>Launch report: ${launchSlug}</h1>
  <p class="subtitle">Generated by the Product Launch Agent — open this file directly in your browser.</p>

  <div class="summary">${summary.replace(/</g, '&lt;')}</div>

  ${contentSections}

  <div class="asset-section">
    <h2>Assets produced</h2>
    <div class="asset-grid">
      ${assetGrid}
    </div>
  </div>
</body>
</html>`;
}
